volumes:
  agencemysql:

networks:
    wpnet:
      driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: agencesqlctn
    restart: unless-stopped
    env_file: .env
    ports:
      - "3310:3306"
    volumes:
      - agencemysql:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wpnet